### ISSUE TITLE
Travis email notifications

### ISSUE THREAD

**Issue by massix** [orwell-int/server-game#29]
@The next one that will do a pull request:
would you please add the following at the .travis.yml file?

```
notifications:
  recipients:
    - massimo.gengarelli@gmail.com
  email:
    on_success: change
    on_failure: always
```

(ref: [another config](https://github.com/rubinius/rubinius/blob/master/.travis.yml))

Feel free to add your emails too or to setup an IRC channel (that would be cool)
